const {chromium}=require(process.env.CPI_PLAYWRIGHT || 'C:/Users/luis_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
let browser;
(async()=>{
 const out=process.argv[3]||'work/inflation_dashboard_r32_preview',url=process.argv[2]||'http://127.0.0.1:8766';
 fs.mkdirSync(out,{recursive:true});
 browser=await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);
 await page.locator('#metrics .metric').last().waitFor();
 await page.screenshot({path:out+'/overview.png',fullPage:true});
 await page.getByRole('button',{name:'Change · 3m',exact:true}).click();
 if(!(await page.locator('#driver-caption').textContent()).includes('3 months'))throw Error('Driver toggle failed');
 await page.getByRole('button',{name:'02 Forecasts & CNB',exact:true}).click();
 await page.locator('#path-version').selectOption('archive');
 await page.locator('#path-version').selectOption('rebased');
 await page.getByRole('button',{name:'CNB rounds replay',exact:true}).click();
 await page.locator('#report-select').selectOption('8');
 await page.locator('#clock-select').selectOption('cutoff');
 await page.locator('[data-model="ROSTER_R27"]').uncheck();
 await page.locator('[data-model="FAST"]').check();
 if(!(await page.locator('#replay-quarter-table thead').textContent()).includes('FAST reference'))throw Error('Quarter table does not follow selected model');
 await page.locator('[data-model="ROSTER_R27"]').check();
 await page.locator('[data-model="FAST"]').uncheck();
 await page.getByText('Component paths and the gap to the CNB',{exact:true}).click();
 await page.screenshot({path:out+'/replay.png',fullPage:true});
 if(await page.locator('#replay-chart svg').count()!==1)throw Error('No replay plot');
 await page.getByRole('button',{name:'03 Data & reliability',exact:true}).click();
 await page.locator('#score-sample').selectOption('prints_2024plus');
 if(!(await page.locator('#score-table').textContent()).includes('0.222'))throw Error('Incorrect accepted BASE sample');
 await page.screenshot({path:out+'/data.png',fullPage:true});
 await page.getByRole('button',{name:'01 Overview',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);
 const overflow=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth}));
 if(overflow.body>overflow.viewport+1)throw Error('Mobile page overflows: '+JSON.stringify(overflow));
 await page.screenshot({path:out+'/mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Forecasts & CNB',exact:true}).click();
 await page.getByRole('button',{name:'CNB rounds replay',exact:true}).click();
 await page.screenshot({path:out+'/mobile-replay.png',fullPage:true});
 const mobileOverflow=await page.evaluate(()=>document.body.scrollWidth>innerWidth+1);
 if(mobileOverflow)throw Error('Mobile replay page overflows');
 await browser.close();
 if(errors.length)throw Error('Browser errors: '+errors.join(';'));
 console.log(JSON.stringify({status:'passed',pageErrors:errors,desktop:'1440x1100',mobile:'390x844',screenshots:out,controls:['drivers','view navigation','path vintage','CNB report','CNB clock','model visibility','components','score sample']}));
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});

