const {chromium}=require('C:/Users/luis_/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');let browser;
(async()=>{
 const url=process.argv[2],out=process.argv[3]||'work/r35-browser';fs.mkdirSync(out,{recursive:true});
 browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 await page.locator('#momentum-rows tr').last().waitFor();
 if(await page.locator('#momentum-rows tr').count()!==9)throw Error('Nine categories required');
 if(await page.locator('.heat-cell').count()!==108)throw Error('Twelve-month heatmap incomplete');
 const spark=await page.locator('.momentum-spark').first().evaluate(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,padding:getComputedStyle(e).padding}));if(spark.w<80||spark.h<20||spark.padding!=='0px')throw Error('Sparkline is collapsed '+JSON.stringify(spark));
 const dupes=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return ids.filter((x,i)=>ids.indexOf(x)!==i);});if(dupes.length)throw Error('Duplicate ids: '+dupes);
 const checks=await page.evaluate(()=>({month:MOM.month,forecast:CURRENT.meta.origin,h0:DATA.live.point,weight:MOM.rows.reduce((a,r)=>a+r.weight,0),drivers:MOM.drivers.reduce((a,r)=>a+r.value,0),total:MOM.driver_total_log_pp,breadth:['picking_up','cooling','little_change','missing'].reduce((a,k)=>a+MOM.breadth[k],0)}));
 if(checks.month!=='2026-08'||checks.forecast!=='2026-09'||Math.abs(checks.h0+.2042311894134946)>1e-12||Math.abs(checks.weight-1000)>1e-6||Math.abs(checks.drivers-checks.total)>1e-10||Math.abs(checks.breadth-100)>1e-8)throw Error('Accounting '+JSON.stringify(checks));
 const tableMatches=await page.evaluate(()=>MOM.rows.every(r=>document.querySelector('#momentum-rows tr[data-row="'+r.id+'"] .rate').textContent===nice(r.m3)));if(!tableMatches)throw Error('Displayed category rate does not match analysis');
 const partialLabel=await page.evaluate(()=>{const original={complete:MOM.driver_complete,total:MOM.driver_total_log_pp,coverage:MOM.driver_coverage};MOM.driver_complete=false;MOM.driver_total_log_pp=null;MOM.driver_coverage=80;renderMomentumDrivers();const label=$('momentum-driver-note').textContent;MOM.driver_complete=original.complete;MOM.driver_total_log_pp=original.total;MOM.driver_coverage=original.coverage;renderMomentumDrivers();return label;});if(!partialLabel.includes('Partial categories only')||!partialLabel.includes('Full-basket change unavailable'))throw Error('Partial driver coverage falsely shown as complete');
 await page.screenshot({path:out+'/first-screen.png'});await page.screenshot({path:out+'/overview.png',fullPage:true});
 await page.locator('#momentum-sort').selectOption('up');
 const order=await page.locator('#momentum-rows tr').evaluateAll(nodes=>nodes.map(n=>n.dataset.row));
 const expected=await page.evaluate(()=>[...MOM.rows].sort((a,b)=>a.acceleration==null?1:b.acceleration==null?-1:b.acceleration-a.acceleration).map(r=>r.id));if(JSON.stringify(order)!==JSON.stringify(expected))throw Error('Sort is incorrect');
 await page.locator('#momentum-sort').selectOption('basket');
 await page.locator('#momentum-rows [data-category="catering"]').click();
 await page.locator('#category-dialog').waitFor({state:'visible'});await page.locator('#category-series').selectOption('accommodation');
 if(!(await page.locator('#category-title').textContent()).includes('Accommodation'))throw Error('Underlying group selection failed');
 if(!(await page.locator('#category-chart svg').textContent()).includes('annualised / y/y'))throw Error('Momentum chart falsely labeled yoy');
 await page.screenshot({path:out+'/category.png'});await page.keyboard.press('Escape');
 await page.locator('[data-heat="acceleration"]').click();
 if(!(await page.locator('#heatmap-caption').textContent()).includes('preceding'))throw Error('Acceleration legend missing');
 await page.locator('.heat-cell').first().focus();await page.waitForTimeout(80);
 if(!(await page.locator('#tooltip').textContent()).includes('Change in pace'))throw Error('Keyboard heatmap tooltip missing');
 await page.keyboard.press('Escape');await page.locator('[data-heat="m3"]').click();
 await page.locator('#momentum-method-open').click();if(!(await page.locator('#momentum-method-content').textContent()).includes('geometric'))throw Error('Aggregation definition missing');await page.locator('#momentum-method-close').click();
 await page.getByRole('button',{name:'02 Forecasts & CNB',exact:true}).click();
 if(await page.locator('#path-chart svg').count()!==1)throw Error('Current path lost');
 const neutral=await page.evaluate(()=>scenarioRows(0,0,0));if(neutral.some(r=>r.baseline_yy!==r.scenario_yy))throw Error('Scenario baseline changed');
 await page.locator('#uncertainty-sample').selectOption('full');await page.locator('#current-gap-quarter').selectOption('2026Q4');
 await page.getByRole('button',{name:'CNB rounds replay',exact:true}).click();await page.locator('#report-select').selectOption('8');await page.locator('#clock-select').selectOption('cutoff');
 await page.locator('[data-model="FAST"]').check();await page.locator('[data-model="ROSTER_R27"]').uncheck();
 if(await page.locator('#replay-chart svg').count()!==1)throw Error('CNB replay lost');await page.screenshot({path:out+'/replay.png',fullPage:true});
 await page.getByRole('button',{name:'03 Data & reliability',exact:true}).click();await page.locator('.legacy-overview>summary').click();
 if(!(await page.locator('.legacy-overview').textContent()).includes('July'))throw Error('Archive not dated');
 await page.getByRole('button',{name:'01 Overview',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(180);
 if(await page.evaluate(()=>document.body.scrollWidth>innerWidth+1))throw Error('Mobile page overflow');
 await page.screenshot({path:out+'/mobile.png',fullPage:true});await page.screenshot({path:out+'/mobile-first-screen.png'});
 await page.locator('#momentum-rows [data-category="food"]').click();
 if(await page.evaluate(()=>document.querySelector('#category-dialog').getBoundingClientRect().width>innerWidth))throw Error('Mobile dialog overflow');
 await page.screenshot({path:out+'/mobile-category.png'});await page.keyboard.press('Escape');
 await browser.close();if(errors.length)throw Error('JS errors '+errors.join('; '));
 const result={status:'passed',pageErrors:errors,desktop:'1440x1050',mobile:'390x844',checks};fs.writeFileSync(out+'/checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
